export const GET_SERVER_STATUS = "GET_SERVER_STATUS"
export const GET_SERVER_STATUS_SUCCESS = "GET_SERVER_STATUS_SUCCESS"
export const GET_SERVER_STATUS_ERROR = "GET_SERVER_STATUS_ERROR"

export const GET_CONFIGS = "GET_CONFIGS"
export const GET_CONFIGS_SUCCESS = "GET_CONFIGS_SUCCESS"
export const GET_CONFIGS_ERROR = "GET_CONFIGS_ERROR"

export const GET_CONFIG = "GET_CONFIG"
export const GET_CONFIG_SUCCESS = "GET_CONFIG_SUCCESS"
export const GET_CONFIG_ERROR = "GET_CONFIG_ERROR"

export const CHECK_IP_ADDRESS = "CHECK_IP_ADDRESS"
export const CHECK_IP_ADDRESS_SUCCESS = "CHECK_IP_ADDRESS_SUCCESS"
export const CHECK_IP_ADDRESS_ERROR = "CHECK_IP_ADDRESS_ERROR"

export const CHECK_PORT = "CHECK_PORT"
export const CHECK_PORT_SUCCESS = "CHECK_PORT_SUCCESS"
export const CHECK_PORT_ERROR = "CHECK_PORT_ERROR"

export const CHECK_INTERFACE_NAME = "CHECK_INTERFACE_NAME"
export const CHECK_INTERFACE_NAME_SUCCESS = "CHECK_INTERFACE_NAME_SUCCESS"
export const CHECK_INTERFACE_NAME_ERROR = "CHECK_INTERFACE_NAME_ERROR"

export const ADD_NEW_CONFIG = "ADD_NEW_CONFIG"
export const ADD_NEW_CONFIG_SUCCESS = "ADD_NEW_CONFIG_SUCCESS"
export const ADD_NEW_CONFIG_ERROR = "ADD_NEW_CONFIG_ERROR"

export const SWITCH_CONFIG_STATUS = "SWITCH_CONFIG_STATUS"
export const SWITCH_CONFIG_STATUS_SUCCESS = "SWITCH_CONFIG_STATUS_SUCCESS"
export const SWITCH_CONFIG_STATUS_ERROR = "SWITCH_CONFIG_STATUS_ERROR"

export const ADD_NEW_PEER = "ADD_NEW_PEER"
export const ADD_NEW_PEER_SUCCESS = "ADD_NEW_PEER_SUCCESS"
export const ADD_NEW_PEER_ERROR = "ADD_NEW_PEER_ERROR"

export const GET_AVAILABLE_IPS = "GET_AVAILABLE_IPS"
export const GET_AVAILABLE_IPS_SUCCESS = "GET_AVAILABLE_IPS_SUCCESS"
export const GET_AVAILABLE_IPS_ERROR = "GET_AVAILABLE_IPS_ERROR"

export const DELETE_PEER = "DELETE_PEER"
export const DELETE_PEER_SUCCESS = "DELETE_PEER_SUCCESS"
export const DELETE_PEER_ERROR = "DELETE_PEER_ERROR"

export const RESET_CONFIG_CHART_DATA = "RESET_CONFIG_CHART_DATA"

export const GET_CONFIG_CHART_DATA = "GET_CONFIG_CHART_DATA"
export const GET_CONFIG_CHART_DATA_SUCCESS = "GET_CONFIG_CHART_DATA_SUCCESS"
export const GET_CONFIG_CHART_DATA_ERROR = "GET_CONFIG_CHART_DATA_ERROR"

export const RESET_PEER_CHART_DATA = "RESET_PEER_CHART_DATA"
export const GET_PEER_CHART_DATA = "GET_PEER_CHART_DATA"
export const GET_PEER_CHART_DATA_SUCCESS = "GET_PEER_CHART_DATA_SUCCESS"
export const GET_PEER_CHART_DATA_ERROR = "GET_PEER_CHART_DATA_ERROR"

export const CHANGE_PEER_STATE = "CHANGE_PEER_STATE"
export const CHANGE_PEER_STATE_SUCCESS = "CHANGE_PEER_STATE_SUCCESS"
export const CHANGE_PEER_STATE_ERROR = "CHANGE_PEER_STATE_ERROR"

export const UPDATE_PEER_SETTINGS = "UPDATE_PEER_SETTINGS"
export const UPDATE_PEER_SETTINGS_SUCCESS = "UPDATE_PEER_SETTINGS_SUCCESS"
export const UPDATE_PEER_SETTINGS_ERROR = "UPDATE_PEER_SETTINGS_ERROR"

export const UPDATE_LIST_TYPE = "UPDATE_LIST_TYPE"
export const UPDATE_REFRESH_TIME = "UPDATE_REFRESH_TIME"

export const FETCH_CONFIG_FOR_TOOLS = "FETCH_CONFIG_FOR_TOOLS"
export const FETCH_CONFIG_FOR_TOOLS_SUCCESS = "FETCH_CONFIG_FOR_TOOLS_SUCCESS"
export const FETCH_CONFIG_FOR_TOOLS_ERROR = "FETCH_CONFIG_FOR_TOOLS_ERROR"

export const SET_PING = "SET_PING"
export const SET_PING_SUCCESS = "SET_PING_SUCCESS"
export const SET_PING_ERROR = "SET_PING_ERROR"

export const SET_TRACEROUTE = "SET_TRACEROUTE"
export const SET_TRACEROUTE_SUCCESS = "SET_TRACEROUTE_SUCCESS"
export const SET_TRACEROUTE_ERROR = "SET_TRACEROUTE_ERROR"


export const UPDATE_GLOBAL_CONF = "UPDATE_GLOBAL_CONF"

export const UPDATE_ACCOUNT_DATA = "UPDATE_ACCOUNT_DATA"
export const UPDATE_ACCOUNT_DATA_SUCCESS = "UPDATE_ACCOUNT_DATA_SUCCESS"
export const UPDATE_ACCOUNT_DATA_ERROR = "UPDATE_ACCOUNT_DATA_ERROR"

